apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodeployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: democontainer
        image: mohitgaur1272/demo:latest
        ports:
        - containerPort: 80
        resources:
         limits:
           cpu: 100m
         requests:
           cpu: 50m

---
apiVersion: v1
kind: Service
metadata:
  name: demosvc
spec:
  selector:
    app: demo
  ports:
  - port: 80
    targetPort: 80
---
